# Default values for open5gs-epc-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

open5gs:
  image:
    repository: umakantk/open5gs
    pullPolicy: Always
    tag: "35f4cf8_mongo"

pcs:
  enableNodeAffinity: true
  dbCommEnabled:
    amf: true
    smf: true
    upf: true
  upsertApiEnabled:
    amf:
      create: false
    smf:
      create: false
    upf:
      create: false
  updateApiEnabled:
    amf:
      n1n2: true
      modify: true
    smf:
      n1n2: true
      modify: true
    upf:
      modify: true
  replaceApiEnabled:
    amf:
      n1n2: false
      modify: false
    smf:
      n1n2: false
      modify: false
    upf:
      modify: false
  blockingApiEnabled:
    amf:
      create: true
      n1n2: true
      modifyreq: true
      modifyrsp: true
    upf:
      create: true
      modifyrsp: true

  isProceduralStateless:
    amf: false
    smf: false
    upf: false
  dbCollectioname:
    amf: "amf"
    smf: "smf"
    upf: "upf"

pool:
  key: 128
  val: 65536

max:
  ue: 2048

ueransim:
  image:
    repository: umakantk/ueransim
    pullPolicy: Always
    tag: "v0.4"

mongodb:
  image:
    repository: umakantk/open5gs-mongo
    pullPolicy: IfNotPresent
    tag: "v0.2"

webui:
  image:
    repository: registry.gitlab.com/infinitydon/registry/open5gs-webui
    pullPolicy: Always
    tag: "v2.2.2"
  ingress:
    enabled: false
    ## Ingress annotations done as key:value pairs
    ## For a full list of possible ingress annotations, please see
    ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md
    ##
    ## If tls is set to true, annotation ingress.kubernetes.io/secure-backends: "true" will automatically be set
    # annotations:
    #   kubernetes.io/ingress.class: nginx

    hosts:
      - name: open5gs-epc.local
        paths: ["/"]
        ## Set this to true in order to enable TLS on the ingress record
        tls: false

        ## Optionally specify the TLS hosts for the ingress record
        ## Useful when the Ingress controller supports www-redirection
        ## If not specified, the above host name will be used
        # tlsHosts:
        # - www.open5gs-epc.local
        # - open5gs-epc.local

        ## If TLS is set to true, you can declare what secret will store the key/certificate for TLS
        # tlsSecret: open5gs-epc.local-tls

dnn: internet

amf:
  mcc: 208
  mnc: 93
  tac: 1

# Primary/Native kubernetes interface
k8s:
  interface: eth0
