FROM mongo:focal

RUN apt -y update

RUN apt -y install git vim python3-pip 

RUN pip3 install pymongo

WORKDIR /root/

RUN git clone https://github.com/UmakantKulkarni/scripts && cd scripts && chmod +x *

RUN sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mongod.conf.orig