FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ARG ARG_TIMEZONE=America/Indiana/Indianapolis
ENV ENV_TIMEZONE=${ARG_TIMEZONE}

RUN apt -y update

RUN apt-get update && apt-get -yq dist-upgrade && apt-get --no-install-recommends -qqy install wget git vim nano make g++ libsctp-dev lksctp-tools net-tools iproute2 libssl-dev tcpdump tshark curl jq iputils-ping gdb python3-pip tzdata openssh-client cmake gnupg

ENV TZ="America/Indiana/Indianapolis"

RUN pip3 install pymongo scapy

RUN cmake --version

ENV PCS_SETUP_TUN_INTF=true

RUN cd && git clone -b ztx_demo_aug https://github.com/UmakantKulkarni/UERANSIM && cd UERANSIM && make

# Define the Go version to install
ENV GO_VERSION=1.24.4
RUN cd && wget https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz && tar -C /usr/local -xzf go${GO_VERSION}.linux-amd64.tar.gz && rm go${GO_VERSION}.linux-amd64.tar.gz
ENV PATH="/usr/local/go/bin:$PATH"
RUN go version
RUN cd && git clone https://github.com/UmakantKulkarni/gnbsim && cd gnbsim && go build
RUN cd

WORKDIR /root/

RUN git clone -b ztx_demo_aug https://github.com/UmakantKulkarni/scripts && cd scripts && chmod +x * 

RUN git clone https://github.com/UmakantKulkarni/5GUnSec && cd 5GUnSec && chmod +x *

RUN cp UERANSIM/build/nr-* /usr/local/bin/

# sync timezone
RUN echo '$ENV_TIMEZONE' > /etc/timezone \
    && ln -fsn /usr/share/zoneinfo/$ENV_TIMEZONE /etc/localtime \
    && dpkg-reconfigure --frontend noninteractive tzdata

RUN wget https://downloads.mongodb.com/compass/mongodb-mongosh_2.3.6_amd64.deb && \
    dpkg -i mongodb-mongosh_2.3.6_amd64.deb && \
    mongosh --version

CMD ["sh", "-c", "sleep infinity"]
