FROM mongo:4-focal

ARG ARG_TIMEZONE=America/Indiana/Indianapolis
ENV ENV_TIMEZONE ${ARG_TIMEZONE}

RUN apt -y update

RUN apt -y install git vim python3-pip tzdata

ENV TZ="America/Indiana/Indianapolis"

RUN pip3 install pymongo

WORKDIR /root/

RUN git clone -b ztx_01 https://github.com/UmakantKulkarni/scripts && cd scripts && chmod +x *

RUN sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mongod.conf.orig

# sync timezone
RUN echo '$ENV_TIMEZONE' > /etc/timezone \
    && ln -fsn /usr/share/zoneinfo/$ENV_TIMEZONE /etc/localtime \
    && dpkg-reconfigure --frontend noninteractive tzdata
