apiVersion: v1
kind: Service
metadata:
  name: amf-open5gs-sctp
  labels:
    epc-mode: amf
spec:
  type: LoadBalancer
  selector:
    epc-mode: amf
  ports:
    - protocol: SCTP
      port: 38412
      targetPort: 38412
      nodePort: 30412
---
apiVersion: v1
kind: Service
metadata:
  name: open5gs-amf
  labels:
    epc-mode: amf
spec:
  selector:
    epc-mode: amf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-amf-deployment
  labels:
    epc-mode: amf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: amf
  template:
    metadata:
      labels:
        epc-mode: amf
    spec:
      containers:
        - name: amf
          image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
          imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          command: ["open5gs-amfd", "-c", "/open5gs/config-map/amf.yaml"]
          env:
          - name: PCS_DB_COMM_ENABLED
            value: {{ .Values.open5gs.pcsDbCommEnabled.amf | default false }}
          volumeMounts:
          - name: open5gs-amf-config
            mountPath: /open5gs/config-map/amf.yaml
            subPath: "amf.yaml"
      volumes:
        - name: open5gs-amf-config
          configMap:
            name: open5gs-amf-config
