apiVersion: v1
kind: Service
metadata:
  name: amf-open5gs-sctp
  labels:
    epc-mode: amf
spec:
  type: LoadBalancer
  selector:
    epc-mode: amf
  ports:
    - protocol: SCTP
      port: 38412
      targetPort: 38412
      nodePort: 30412
---
apiVersion: v1
kind: Service
metadata:
  name: open5gs-amf
  labels:
    epc-mode: amf
spec:
  selector:
    epc-mode: amf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-amf-deployment
  labels:
    epc-mode: amf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: amf
  template:
    metadata:
      labels:
        epc-mode: amf
    spec:
      {{ if .Values.pcs.enableNodeAffinity }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/pcs-nf-type
                operator: In
                values:
                - amf
      {{ end }}
      containers:
        - name: amf
          image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
          imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          command: ["open5gs-amfd", "-c", "/open5gs/config-map/amf.yaml"]
          env:
          - name: PCS_DB_COMM_ENABLED
            value: {{ .Values.pcs.dbCommEnabled.amf | default "false" }}
          - name: PCS_UPSERT_API_ENABLED_CREATE
            value: {{ .Values.pcs.upsertApiEnabled.amf.create | default "true" }}
          - name: PCS_UPDATE_API_ENABLED_N1N2
            value: {{ .Values.pcs.updateApiEnabled.amf.n1n2 | default "true" }}
          - name: PCS_UPDATE_API_ENABLED_MODIFY
            value: {{ .Values.pcs.updateApiEnabled.amf.modify | default "true" }}
          - name: PCS_REPLACE_API_ENABLED_N1N2
            value: {{ .Values.pcs.replaceApiEnabled.amf.n1n2 | default "true" }}
          - name: PCS_REPLACE_API_ENABLED_MODIFY
            value: {{ .Values.pcs.replaceApiEnabled.amf.modify | default "true" }}
          - name: PCS_BLOCKING_API_ENABLED_CREATE
            value: {{ .Values.pcs.blockingApiEnabled.amf.create | default "true" }}
          - name: PCS_BLOCKING_API_ENABLED_N1N2
            value: {{ .Values.pcs.blockingApiEnabled.amf.n1n2 | default "false" }}
          - name: PCS_BLOCKING_API_ENABLED_MODIFYREQ
            value: {{ .Values.pcs.blockingApiEnabled.amf.modifyreq | default "false" }}
          - name: PCS_BLOCKING_API_ENABLED_MODIFYRSP
            value: {{ .Values.pcs.blockingApiEnabled.amf.modifyrsp | default "false" }}
          - name: PCS_IS_PROCEDURAL_STATELESS
            value: {{ .Values.pcs.isProceduralStateless.amf | default "false" }}
          - name: PCS_DB_COLLECTION_NAME
            value: {{ .Values.pcs.dbCollectioname.amf | default "amf" }}
          - name: PCS_ENABLE_SINGLE_READ
            value: {{ .Values.pcs.enableSingleRead.amf | default "false" }}
          - name: DB_URI
            {{ if .Values.pcs.enableNodeAffinity }}
            value: {{ .Values.mongodb.rsuri.amf }}
            {{ else }}
            value: {{ .Values.mongodb.sauri.amf }}
            {{ end }}
          volumeMounts:
          - name: open5gs-amf-config
            mountPath: /open5gs/config-map/amf.yaml
            subPath: "amf.yaml"
      volumes:
        - name: open5gs-amf-config
          configMap:
            name: open5gs-amf-config
