apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-ausf-config
  labels:
    epc-mode: ausf
data:
  ausf.yaml: |
    logger:
        file: /var/log/open5gs/ausf.log
    time:
      t3512:
        value: 540
    sbi:
      server:
        no_tls: true
      client:
        no_tls: true
    ausf:
      sbi:
      - addr: 0.0.0.0
        advertise: open5gs-ausf
    nrf:
     sbi:
      name: open5gs-nrf
    pool:
      {{ .Values.pool.key }}: {{ .Values.pool.val }}
    max:
      ue: {{ .Values.max.ue }}
