apiVersion: v1
kind: Service
metadata:
  name: open5gs-ausf
  labels:
    epc-mode: ausf
spec:
  selector:
    epc-mode: ausf
  ports:
    - protocol: TCP
      port: 80   
      targetPort: 80
---  
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-ausf-deployment
  labels:
    epc-mode: ausf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: ausf
  template:
    metadata:
      labels:
        epc-mode: ausf
    spec:    
      containers:
        - name: ausf
          image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
          imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          command: ["open5gs-ausfd", "-c", "/open5gs/config-map/ausf.yaml"]
          volumeMounts:
          - name: open5gs-ausf-config
            mountPath: /open5gs/config-map/ausf.yaml
            subPath: "ausf.yaml"
      volumes:
        - name: open5gs-ausf-config
          configMap:
            name: open5gs-ausf-config