apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-bsf-config
  labels:
    epc-mode: bsf
data:
  bsf.yaml: |
    logger:
        file: /var/log/open5gs/bsf.log

    {{ if .Values.pcs.enableNodeAffinity }}
    db_uri: {{ .Values.mongodb.rsuri.bsf }}
    {{ else }}
    db_uri: {{ .Values.mongodb.sauri.bsf }}
    {{ end }}
    bsf:
      sbi:
      - addr: 0.0.0.0
        advertise: open5gs-bsf
    nrf:
     sbi:
      name: open5gs-nrf
    pool:
      {{ .Values.pool.key }}: {{ .Values.pool.val }}
    max:
      ue: {{ .Values.max.ue }}
