apiVersion: v1
kind: Service
metadata:
  name: open5gs-bsf
  labels:
    epc-mode: bsf
spec:
  selector:
    epc-mode: bsf
  ports:
    - protocol: TCP
      port: 80   
      targetPort: 80
---  
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-bsf-deployment
  labels:
    epc-mode: bsf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: bsf
  template:
    metadata:
      labels:
        epc-mode: bsf
    spec:
      {{ if .Values.pcs.enableNodeAffinity }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/pcs-nf-type
                operator: In
                values:
                - bsf
      {{ end }}
      containers:
        - name: bsf
          image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
          imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          command: ["open5gs-bsfd", "-c", "/open5gs/config-map/bsf.yaml"]
          volumeMounts:
          - name: open5gs-bsf-config
            mountPath: /open5gs/config-map/bsf.yaml
            subPath: "bsf.yaml"
      volumes:
        - name: open5gs-bsf-config
          configMap:
            name: open5gs-bsf-config