{{- if .Values.monitoring.fluentBit.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: {{ .Release.Namespace }}
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf

    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Parser            docker
        Tag               kube.*
        Refresh_Interval  5
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On

    [FILTER]
        Name                kubernetes
        Match               kube.*
        Merge_Log           On
        Kube_Tag_Prefix     kube.var.log.containers.
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On

    [FILTER]
        Name    grep
        Match   kube.*
        Regex   $kubernetes['namespace_name']  {{ .Release.Namespace }}

    [OUTPUT]
        Name          http
        Match         *
        Host          {{ .Values.monitoring.fluentBit.httpEndpoint.host }}
        Port          {{ .Values.monitoring.fluentBit.httpEndpoint.port }}
        URI           {{ .Values.monitoring.fluentBit.httpEndpoint.uri }}
        Format        json
        tls           {{ .Values.monitoring.fluentBit.httpEndpoint.tls | ternary "On" "Off" }}
        json_date_key timestamp
        json_date_format iso8601

  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit-sa
  namespace: {{ .Release.Namespace }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluent-bit
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      serviceAccountName: fluent-bit-sa
      containers:
        - name: fluent-bit
          image: cr.fluentbit.io/fluent/fluent-bit:2.2.2
          securityContext:
            runAsUser: 0
            privileged: true
          command: ["/bin/sh", "-c"]
          args:
            - ulimit -n 65536 && exec /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: config
              mountPath: /fluent-bit/etc/
          resources:
            limits:
              memory: 100Mi
              cpu: 100m
            requests:
              memory: 50Mi
              cpu: 50m
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: config
          configMap:
            name: fluent-bit-config
{{- end }}