apiVersion: v1
kind: Service
metadata:
  name: open5gs-nrf
  labels:
    epc-mode: nrf
spec:
  selector:
    epc-mode: nrf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---    
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-nrf-deployment
  labels:
    epc-mode: nrf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: nrf
  template:
    metadata:
#      annotations:
#        "helm.sh/hook": pre-install    
      labels:
        epc-mode: nrf
    spec:
      {{ if .Values.pcs.nodeAffinity.enabled }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: pcs-nf-type
                operator: In
                values:
                - {{ .Values.pcs.nodeAffinity.nrf | quote }}
      {{ end }}
      containers:
        - name: nrf
          image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
          imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          command: ["open5gs-nrfd", "-c", "/configs/nrf.yaml.in"]
          env:
          - name: DB_URI
            {{ if .Values.pcs.enableMongoReplicaSet }}
            value: {{ .Values.mongodb.rsuri.nrf | quote }}
            {{ else }}
            value: {{ .Values.mongodb.sauri.nrf | quote }}
            {{ end }}
          volumeMounts:
            - name: open5gs-nrf-config
              mountPath: /configs/nrf.yaml.in
              subPath: "nrf.yaml"
      # volumes:
      #   - name: open5gs-nrf-config
      #     configMap:
      #       name: open5gs-nrf-config

