apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-nssf-config
  labels:
    epc-mode: nssf
data:
  nssf.yaml: |
    logger:
      file: /var/log/open5gs/nssf.log
    #  level: info   # fatal|error|warn|info(default)|debug|trace

    global:
      max:
        ue: 1024  # The number of UE can be increased depending on memory size.
    #    peer: 64

    nssf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 80
            advertise: open5gs-nssf
            no_tls: true
        client:
          no_tls: true
    #      nrf:
    #        - uri: http://open5gs-nrf:80
          scp:
            - uri: http://open5gs-scp:80
          nsi:
            - uri: http://open5gs-nrf:80
              s_nssai:
                sst: 1