apiVersion: v1
kind: ServiceAccount
metadata:
  name: open5gs
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: service-and-endpoint-reader
rules:
- apiGroups: [""]
  resources: ["endpoints", "services", "pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-and-endpoint-binding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: open5gs
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: service-and-endpoint-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: open5gs-cluster-service-reader-{{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["namespaces", "services"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: open5gs-cluster-service-binding-{{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: open5gs
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: open5gs-cluster-service-reader-{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
