apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-test-deployment
spec:
  selector:
    matchLabels:
      app: open5gs-test
  replicas: 1
  template:
    metadata:
      labels:
        app: open5gs-test
    spec:
      {{ if .Values.pcs.enableNodeAffinity }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/pcs-nf-type
                operator: In
                values:
                - bsf
      {{ end }}
      containers:
      - name: myapp-container
        image: "{{ .Values.ueransim.image.repository }}:{{ .Values.ueransim.image.tag }}"
        imagePullPolicy: {{ .Values.ueransim.image.pullPolicy }}
        securityContext:
          privileged: true
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "sleep infinity"]
