apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-test-deployment
spec:
  selector:
    matchLabels:
      app: open5gs-test
  replicas: 1
  template:
    metadata:
      labels:
        app: open5gs-test
    spec:
      containers:
      - name: myapp-container
        image: umakantk/ueransim:v0.1
        securityContext:
          privileged: true
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "sleep infinity"]
      initContainers:
      - name: init-network-client
        image: sdnvortex/network-controller:v0.4.9
        command: ["/go/bin/client"]
        args: ["-s=unix:///tmp/vortex.sock", "-b=br0", "-n=eth1", "-i=192.168.2.210/23"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_UUID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        volumeMounts:
        - mountPath: /tmp/
          name: grpc-sock
      volumes:
      - name: grpc-sock
        hostPath:
          path: /tmp/vortex/
