apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-pcf-config
  labels:
    epc-mode: pcf
data:
  pcf.yaml: |
    db_uri: {{ .Values.mongodb.sauri.pcf | quote }}
    logger:
      file: /var/log/open5gs/pcf.log
    #  level: info   # fatal|error|warn|info(default)|debug|trace

    global:
      max:
        ue: 1024  # The number of UE can be increased depending on memory size.
    #    peer: 64

    pcf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 80
            advertise: open5gs-pcf
            no_tls: true
        client:
          no_tls: true
    #      nrf:
    #        - uri: http://open5gs-nrf:80
          scp:
            - uri: http://open5gs-scp:80
      metrics:
        server:
          - address: 0.0.0.0
            port: 9090