apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-pcf-config
  namespace: 5g-core
  labels:
    epc-mode: pcf
data:
  pcf.yaml: |
    logger:
        file: /var/log/open5gs/pcf.log
    
    db_uri: mongodb-svc      

    pcf:
      sbi:     
      - addr: 0.0.0.0
        advertise: open5gs-pcf
    nrf:
     sbi:
      name: open5gs-nrf 