apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-pcf-config
  labels:
    epc-mode: pcf
data:
  pcf.yaml: |
    logger:
        file: /var/log/open5gs/pcf.log
    
    {{ if .Values.pcs.enableNodeAffinity }}
    db_uri: {{ .Values.mongodb.rsuri.pcf | quote }}
    {{ else }}
    db_uri: {{ .Values.mongodb.sauri.pcf | quote }}
    {{ end }}

    pcf:
      sbi:     
      - addr: 0.0.0.0
        advertise: open5gs-pcf
    nrf:
     sbi:
      name: open5gs-nrf
    pool:
      {{ .Values.pool.key }}: {{ .Values.pool.val }}
    max:
      ue: {{ .Values.max.ue }}