apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-smf-config
  labels:
    epc-mode: smf
data:
  smf.yaml: |
    logger:
        file: /var/log/open5gs/smf.log
    time:
      t3512:
        value: 540
    sbi:
      server:
        no_tls: true
      client:
        no_tls: true
    parameter:
        no_ipv6: true

    smf:
        sbi:     
        - addr: 0.0.0.0
          advertise: open5gs-smf
        pfcp:
           dev: {{ .Values.k8s.interface }}
        gtpc:
          dev: {{ .Values.k8s.interface }}
        gtpu:
          dev: {{ .Values.k8s.interface }}    
        subnet:
         - addr: 10.45.0.1/16
           dnn: {{ .Values.dnn }}
        dns:
          - 8.8.8.8
          - 8.8.4.4
        mtu: 1400

    nrf:
     sbi:
      name: open5gs-nrf 

    upf:
      pfcp:
        - name: open5gs-upf
          dnn: {{ .Values.dnn }}
    pool:
      {{ .Values.pool.key }}: {{ .Values.pool.val }}
    max:
      ue: {{ .Values.max.ue }}