apiVersion: v1
kind: Service
metadata:
  name: open5gs-smf
  labels:
    epc-mode: smf
spec:
  selector:
    epc-mode: smf
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 80  
---  
apiVersion: v1
kind: Service
metadata:
  name: open5gs-pfcp
  labels:
    epc-mode: smf
spec:
  type: LoadBalancer
  selector:
    epc-mode: smf
  ports:
    - protocol: UDP
      port: 8805
      targetPort: 8805    
      nodePort:  {{ .Values.open5gs.smf.port | default 30805 }}
--- 
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-smf-deployment
  labels:
    epc-mode: smf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: smf
  template:
    metadata:       
      labels:
        epc-mode: smf
    spec:
      {{ if .Values.pcs.nodeAffinity.enabled }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: pcs-nf-type
                operator: In
                values:
                - {{ .Values.pcs.nodeAffinity.smf | quote }}
      {{ end }}
      {{- include "ztxInitContainer" . | nindent 6 }}
      containers:
        {{- include "ztxAppTemplate" . | nindent 8 }}
        - name: smf
          image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
          imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          env:
            - name: PCS_DB_COMM_ENABLED
              value: {{ .Values.pcs.dbCommEnabled.smf | default "false" | quote }}
            - name: PCS_UPSERT_API_ENABLED_CREATE
              value: {{ .Values.pcs.upsertApiEnabled.smf.create | default "false" | quote }}
            - name: PCS_UPDATE_API_ENABLED_N1N2
              value: {{ .Values.pcs.updateApiEnabled.smf.n1n2 | default "true" | quote }}
            - name: PCS_UPDATE_API_ENABLED_MODIFY
              value: {{ .Values.pcs.updateApiEnabled.smf.modify | default "true" | quote }}
            - name: PCS_REPLACE_API_ENABLED_N1N2
              value: {{ .Values.pcs.replaceApiEnabled.smf.n1n2 | default "false" | quote }}
            - name: PCS_REPLACE_API_ENABLED_MODIFY
              value: {{ .Values.pcs.replaceApiEnabled.smf.modify | default "false" | quote }}
            - name: PCS_IS_PROCEDURAL_STATELESS
              value: {{ .Values.pcs.isProceduralStateless.smf | default "false" | quote }}
            - name: PCS_DB_COLLECTION_NAME
              value: {{ .Values.pcs.dbCollectioname.smf | default "smf" | quote }}
            - name: PCS_ENABLE_SINGLE_READ
              value: {{ .Values.pcs.enableSingleRead.smf | default "false" | quote }}
            - name: DB_URI
              {{ if .Values.pcs.enableMongoReplicaSet }}
              value: {{ .Values.mongodb.rsuri.smf | quote }}
              {{ else }}
              value: {{ .Values.mongodb.sauri.smf | quote }}
              {{ end }}
            - name: OGS_PFCP_UDP_PORT
              value: {{ .Values.open5gs.pfcp.port | default "8805" | quote }}
            - name: OGS_TUN_INTERFACE
              value: {{ .Values.open5gs.pfcp.tunintf | default "ogstun" | quote }}
            - name: OGS_GTPV1_U_UDP_PORT
              value: {{ .Values.open5gs.gtpv1.port | default "2152" | quote }}
            - name: OGS_GTPV2_C_UDP_PORT
              value: {{ .Values.open5gs.gtpv2.port | default "2153" | quote }}
          command: ["/bin/sh", "-c"]
          args:
          - open5gs-smfd -c /open5gs/config-map/smf.yaml;
          volumeMounts:
            - name: open5gs-smf-config
              mountPath: /open5gs/config-map/smf.yaml
              subPath: "smf.yaml"                                       
      volumes:
        - name: open5gs-smf-config
          configMap:
            name: open5gs-smf-config                
