apiVersion: v1
kind: Service
metadata:
  name: open5gs-udm
  labels:
    epc-mode: udm
spec:
  selector:
    epc-mode: udm
  ports:
    - protocol: TCP
      port: 80   
      targetPort: 80
---  
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-udm-deployment
  labels:
    epc-mode: udm
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: udm
  template:
    metadata:
      labels:
        epc-mode: udm
    spec:
      {{ if .Values.pcs.nodeAffinity.enabled }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: pcs-nf-type
                operator: In
                values:
                - {{ .Values.pcs.nodeAffinity.udm | quote }}
      {{ end }}
      containers:
        - name: udm
          image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
          imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          command: ["open5gs-udmd", "-c", "/open5gs/config-map/udm.yaml"]
          env:
          - name: DB_URI
            {{ if .Values.pcs.enableMongoReplicaSet }}
            value: {{ .Values.mongodb.rsuri.udm | quote }}
            {{ else }}
            value: {{ .Values.mongodb.sauri.udm | quote }}
            {{ end }}
          volumeMounts:
          - name: open5gs-udm-config
            mountPath: /open5gs/config-map/udm.yaml
            subPath: "udm.yaml"
      volumes:
        - name: open5gs-udm-config
          configMap:
            name: open5gs-udm-config