apiVersion: v1
kind: Service
metadata:
  name: open5gs-udr
  labels:
    epc-mode: udr
spec:
  selector:
    epc-mode: udr
  ports:
    - protocol: TCP
      port: 80   
      targetPort: 80
---  
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-udr-deployment
  labels:
    epc-mode: udr
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: udr
  template:
    metadata:
      labels:
        epc-mode: udr
    spec:
      {{ if .Values.pcs.nodeAffinity.enabled }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: pcs-nf-type
                operator: In
                values:
                - {{ .Values.pcs.nodeAffinity.udr | quote }}
      {{ end }}
      containers:
        - name: udr
          image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
          imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          command: ["open5gs-udrd", "-c", "/configs/udr.yaml.in"]
          env:
          - name: DB_URI
            {{ if .Values.pcs.enableMongoReplicaSet }}
            value: {{ .Values.mongodb.rsuri.udr | quote }}
            {{ else }}
            value: {{ .Values.mongodb.sauri.udr | quote }}
            {{ end }}
          volumeMounts:
          - name: open5gs-udr-config
            mountPath: /configs/udr.yaml.in
            subPath: "udr.yaml"          
      volumes:
        - name: open5gs-udr-config
          configMap:
            name: open5gs-udr-config