apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-upf-config
  labels:
    epc-mode: upf
data:
  upf.yaml: |
    logger:
      file: /var/log/open5gs/upf.log
    #  level: info   # fatal|error|warn|info(default)|debug|trace

    global:
      max:
        ue: 1024  # The number of UE can be increased depending on memory size.
    #    peer: 64

    upf:
      pfcp:
        server:
          - address: 0.0.0.0
            port: 8805
    #        advertise: open5gs-upf
        client:
          smf:     #  UPF PFCP Client try to associate SMF PFCP Server
            - address: open5gs-smf
      gtpu:
        server:
          - address: 0.0.0.0
      session:
        - subnet: 10.45.0.1/16
        - subnet: 2001:db8:cafe::1/48
      metrics:
        server:
          - address: 0.0.0.0
            port: 9090