apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-upf-config
  labels:
    epc-mode: upf
data:
  upf.yaml: |
    logger:
        file: /var/log/open5gs/upf.log
    time:
      t3512:
        value: 540
    sbi:
      server:
        no_tls: true
      client:
        no_tls: true
    upf:
        pfcp:
           dev: {{ .Values.k8s.upf_interface }}
        gtpu:
           dev: {{ .Values.k8s.upf_interface }}
        subnet:
          - addr: 10.45.0.1/16
            dnn: {{ .Values.dnn }}
    pool:
      {{ .Values.pool.key }}: {{ .Values.pool.val }}
    max:
      ue: {{ .Values.max.ue }}
