apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-upf-config
  labels:
    epc-mode: upf
data:
  upf.yaml: |
    logger:
      file: /var/log/open5gs/upf.log
    #  level: info   # fatal|error|warn|info(default)|debug|trace

    global:
      max:
        ue: 1024  # The number of UE can be increased depending on memory size.
    #    peer: 64

    upf:
      pfcp:
        server:
          - dev: {{ .Values.k8s.podInterface }}
            port: {{ .Values.open5gs.pfcp.port | default 8805 }}
    #        advertise: open5gs-upf
    #    client:
    #      smf:     #  UPF PFCP Client try to associate SMF PFCP Server
    #        - address: 127.0.0.4
      gtpu:
        server:
          - dev: {{ .Values.k8s.podInterface }}
            port: {{ .Values.open5gs.gtpv1.port | default 2152 }}
      session:
        - subnet: 10.45.0.1/16
        - subnet: 2001:db8:cafe::1/48
      # metrics:
      #   server:
      #     - address: 0.0.0.0
      #       port: 9090