apiVersion: v1
kind: Service
metadata:
  name: open5gs-upf
  labels:
    epc-mode: upf
spec:
  selector:
    epc-mode: upf
  ports:
    - protocol: UDP
      port: 8805
      targetPort: {{ .Values.open5gs.pfcp.port | default 8805 }}
---  
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-upf-deployment
  labels:
    epc-mode: upf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: upf
  template:
    metadata:
      annotations:
        linkerd.io/inject: disabled
      labels:
        epc-mode: upf
    spec:
      {{ if .Values.pcs.nodeAffinity.enabled }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: pcs-nf-type
                operator: In
                values:
                - {{ .Values.pcs.nodeAffinity.upf | quote }}
      {{ end }}
      hostNetwork: {{ .Values.open5gs.upf.hostNetwork }}
      {{- include "ztxInitContainer" . | nindent 6 }}
      containers:
        {{- include "ztxAppTemplate" . | nindent 8 }}
        - name: upf
          image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
          imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          env:
          - name: PCS_DB_COMM_ENABLED
            value: {{ .Values.pcs.dbCommEnabled.upf | default "false" | quote }}
          - name: PCS_UPSERT_API_ENABLED_CREATE
            value: {{ .Values.pcs.upsertApiEnabled.upf.create | default "false" | quote }}
          - name: PCS_UPDATE_API_ENABLED_MODIFY
            value: {{ .Values.pcs.updateApiEnabled.upf.modify | default "true" | quote }}
          - name: PCS_REPLACE_API_ENABLED_MODIFY
            value: {{ .Values.pcs.replaceApiEnabled.upf.modify | default "false" | quote }}
          - name: PCS_BLOCKING_API_ENABLED_CREATE
            value: {{ .Values.pcs.blockingApiEnabled.upf.create | default "false" | quote }}
          - name: PCS_BLOCKING_API_ENABLED_MODIFYRSP
            value: {{ .Values.pcs.blockingApiEnabled.upf.modifyrsp | default "false" | quote }}
          - name: PCS_IS_PROCEDURAL_STATELESS
            value: {{ .Values.pcs.isProceduralStateless.upf | default "false" | quote }}
          - name: PCS_DB_COLLECTION_NAME
            value: {{ .Values.pcs.dbCollectioname.upf | default "upf" | quote }}
          - name: PCS_ENABLE_SINGLE_READ
            value: {{ .Values.pcs.enableSingleRead.upf | default "false" | quote }}
          - name: DB_URI
            {{ if .Values.pcs.enableMongoReplicaSet }}
            value: {{ .Values.mongodb.rsuri.upf | quote }}
            {{ else }}
            value: {{ .Values.mongodb.sauri.upf | quote }}
            {{ end }}
          - name: OGS_PFCP_UDP_PORT
            value: {{ .Values.open5gs.pfcp.port | default "8805" | quote }}
          - name: OGS_TUN_INTERFACE
            value: {{ .Values.open5gs.upf.tunintf | default "ogstun" | quote }}
          - name: OGS_GTPV1_U_UDP_PORT
            value: {{ .Values.open5gs.gtpv1.port | default "2152" | quote }}
          - name: OGS_GTPV2_C_UDP_PORT
            value: {{ .Values.open5gs.gtpv2.port | default "2153" | quote }}
          securityContext:
            privileged: true
          command: ["/bin/sh", "-c"]
          args:
          - ip tuntap add name {{ .Values.open5gs.upf.tunintf }} mode tun;
            ip addr add 10.45.0.1/16 dev {{ .Values.open5gs.upf.tunintf }};
            sysctl -w net.ipv6.conf.all.disable_ipv6=1;
            ip link set {{ .Values.open5gs.upf.tunintf }} up;
            sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward";
            iptables -t nat -A POSTROUTING -s 10.45.0.0/16 ! -o {{ .Values.open5gs.upf.tunintf }} -j MASQUERADE;
            open5gs-upfd -c /open5gs/config-map/upf.yaml;
          volumeMounts:
          - name: open5gs-upf-config
            mountPath: /open5gs/config-map/upf.yaml
            subPath: "upf.yaml"
          - mountPath: /dev/net/tun
            name: dev-net-tun            
      volumes:
        - name: open5gs-upf-config
          configMap:
            name: open5gs-upf-config
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
