{{- if and .Values.ztx.enabled .Values.ztx.imagePullSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ztx.imagePullSecret.name }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |-
    {"auths": {"{{ .Values.ztx.imagePullSecret.server }}": {"username": "{{ .Values.ztx.imagePullSecret.username }}", "password": "{{ .Values.ztx.imagePullSecret.password }}", "auth": "{{ printf "%s:%s" .Values.ztx.imagePullSecret.username .Values.ztx.imagePullSecret.password | b64enc }}"}}}
{{- end }}
